version: '3'

services:

  &DB db:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - api/.env
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER} 
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
    depends_on:
      - db

  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    image: burdinbogdan/api-template:latest
    ports:
      - "3000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - api/.env
    environment: 
      DB_URL: *DB
    #   DB_NAME: ${DB_NAME} 
    #   DB_USERNAME: ${DB_USERNAME} 
    #   DB_PASSWORD: ${DB_PASSWORD} 
    #   JWT_SECRET: ${JWT_SECRET} 
    #   PORT: ${PORT} 

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    image: burdinbogdan/admin-panel-template:latest
    ports:
      - "3001:3000"
    depends_on:
      - db
      - api
    restart: always
    env_file:
      - admin-panel/.env

volumes:
  pgdata:
